name: NPM Dependency-Check

on: push 

jobs:
  dependency-check:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    
    # Configure de acordo com a versão do Node.js de seu projeto
    - name: Dependency-Check
      uses: guilhermemarimzup/dependency-vuln-checker@development
