name: Dependency Vuln Checker

on: push 

jobs:
  dependency-vuln-checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Dependency Analysis
      uses: guilhermemarimzup/dependency-vuln-checker@v1
